project:
  type: website
  output-dir: docs

website:
  title: "blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: 
      light: litera
      dark: solar
    css: styles.css
    toc: true

editor: visual

