project:
  type: website
  output-dir: docs

website:
  navbar: 
    title: "Net Zhang"
    right:
      - href: index.qmd
        text: Home
      - posts.qmd
      - resume.qmd
  page-footer: 
    background: light # or dark
    left:
      - "Copyright 2023, Net Zhang"

format:
  html:
    theme: 
      light: litera
      dark: solar
    css: styles.css
    toc: true

editor: visual

