---
title: '"Blog"'
listing: 
  contents: posts # all Quarto docs in the `posts` directory will be included on your listing page
  type: grid # or `default` or `table`; each type has its own set of yaml options to include
  sort: "date desc" # can also sort on more than one field
  categories: true # allows you to sort posts by assigned categories 
---

# About the Posts

The first three posts were generated by LLM. At the time, I liked the idea of building a mental index by leveraging supervision as the knowledge base. However, I found that to be LAZY! I've decided that my future posts will not consist of artificially generated texts. Although I would definitely still use LLM to write text and code, this blog serves the purpose of knowledge sharing and journaling and should be driven by **curiosity** and **originality**. I was simply sick of myself pretending to have intellectual output in the disguise of laziness. **Great things come from hard work...**

The preview image is generally not relevant to the post's content. I enjoy great cinematography. If you can recognize these shots I'll buy you dinner!
